spp:
  image: spp-container
  volumes:
    - "~/dpdk-home:/root/dpdk-home"

runcmd:
  image: spp-container

vhost:
  image: spp-container
  volumes:
    - /tmp/sock0:/var/run/usvhost0
    - /tmp/sock1:/var/run/usvhost1
    - /dev/hugepages:/dev/hugepages

pktgen0:
  image: spp-container
  working_dir: /root/pktgen-dpdk
  volumes:
    - /tmp/sock0:/var/run/usvhost0
    - /dev/hugepages:/dev/hugepages

pktgen1:
  image: spp-container
  working_dir: /root/pktgen-dpdk
  volumes:
    - /tmp/sock1:/var/run/usvhost1
    - /dev/hugepages:/dev/hugepages
