pktgen0:
  image: spp-container
  working_dir: /root/pktgen-dpdk
  volumes:
    - /tmp/sock0:/var/run/usvhost0
    - /dev/hugepages:/dev/hugepages

pktgen1:
  image: spp-container
  working_dir: /root/pktgen-dpdk
  volumes:
    - /tmp/sock1:/var/run/usvhost1
    - /dev/hugepages:/dev/hugepages
