spp-nfv1:
  image: spp-container
  working_dir: /root/pktgen-dpdk
  privileged: true
  volumes:
    - /dev/hugepages:/dev/hugepages
    - /var/run/:/var/run/

spp-vm1:
  image: spp-container
  working_dir: /root/pktgen-dpdk
  volumes:
    - /tmp/sock0:/var/run/usvhost0
    - /tmp/sock1:/var/run/usvhost1
    - /dev/hugepages:/dev/hugepages
    - /var/run/:/var/run/
